# Ratel binary and test environment are built from Dockerfile and Dockerfile.test
# Dgraph server versions are set to 'latest' and can be overriden by setting
#  DGRAPH_VERSION env var
version: "3.7"
services:
  ratel:
    build: ../../..
    ports:
      - 8000

  test:
    build:
      context: ../../..
      dockerfile: test.Dockerfile
    privileged: true
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep 9999999999d & wait"]
    environment:
      TEST_DGRAPH_SERVER: http://e2etests_alpha_1:8080
      TEST_RATEL_URL: http://e2etests_ratel_1:8000?local

  zero:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    ports:
      - 5080
      - 6080
    restart: on-failure
    command: dgraph zero --my=e2etests_zero_1:5080

  alpha:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    volumes:
      - ./acl-secret.txt:/secrets/acl-secret.txt
    ports:
      - 8080
      - 9080
    restart: on-failure
    command:
      dgraph alpha --my=e2etests_alpha_1:7080 --zero=e2etests_zero_1:5080
      --acl='secret-file=/secrets/acl-secret.txt'
      --security='whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16'
